version: "3.8"
services:
  musicsync:
    image: lincolnpark2000/musicsync:latest
    container_name: musicsync
    restart: unless-stopped
    ports:
      # 左侧改为你想要的端口号
      - "5566:5566"
    environment:
      - PORT=5566
      - NODE_ENV=production
      - DATA_DIR=/app/data
      - DOWNLOAD_DIR=/app/downloads
    volumes:
      - musicsync_data:/app/data
      - musicsync_downloads:/app/downloads

volumes:
  musicsync_data:
  musicsync_downloads:
